---
#  vars

rhel_packages:
  - qemu-kvm
  - libvirt
  - libvirt-python
  - libguestfs-tools
  - virt-install

debian_packages:
  - qemu-kvm
  - libvirt-daemon-system
  - libvirt-clients
  - virtinst
