---

- name: Define url of RHCOS dependencies
  set_fact:
    rhcos_url: "{{ rhcos_mirror + '/' + rhcos_ver_majmin + '/' + rhcos_version }}"

- name: Define url of RHCOS checksum
  set_fact:
    rhcos_checksum: "{{ rhcos_url + '/sha256sum.txt' }}"

- name: Download RHCOS sha256sum from {{ rhcos_url }}
  get_url:
    url: "{{ rhcos_checksum }}"
    dest: "{{ matchbox_rhcos_checksum }}"
    owner: matchbox
    group: matchbox

- name: List RHCOS files from checksum file {{ matchbox_rhcos_checksum }}
  command: "awk '/kernel|initramfs|metal/ && /{{ rhcos_ver_majmin }}/' {{ matchbox_rhcos_checksum }}"
  register: rhcos_files

- name: Define name of each RHCOS asset
  set_fact:
    checksum_kernel: "{{ rhcos_files.stdout_lines | select('search','kernel') | list | first }}"
    checksum_initrd: "{{ rhcos_files.stdout_lines | select('search','initramfs') | list | first }}"
    checksum_metal: "{{ rhcos_files.stdout_lines | select('search','metal') | list | first }}"

- name: Split RHCOS asset to have checksum and filename
  set_fact:
    rhcos_kernel: "{{ checksum_kernel.split() | list }}"
    rhcos_initrd: "{{ checksum_initrd.split() | list }}"
    rhcos_metal: "{{ checksum_metal.split() | list }}"

- name: Download RHCOS assets from list of files
  get_url:
    url: "{{ rhcos_url + '/' + item.1 }}"
    dest: "{{ matchbox_assets + '/' + item.1 }}"
    checksum: "{{ 'sha256:' + item.0 }}"
    force: no
    owner: matchbox
    group: matchbox
  loop:
    - "{{ rhcos_kernel }}"
    - "{{ rhcos_initrd }}"
    - "{{ rhcos_metal }}"
