---

- name: Install RHEL/CentOS packages
  package:
    name: "{{ item }}"
  loop: "{{ rhel_packages }}"
  when: ansible_facts['os_family'] == "RedHat"

- name: Install Debian/Ubuntu packages
  package:
    name: "{{ item }}"
  loop: "{{ debian_packages }}"
  when: ansible_facts['os_family'] == "Debian"

- name: Add user ansible to libvirt
  user:
    name: ansible
    groups: libvirt
    append: yes