---

#  These variables are not changed by the input and
#- are intended to be used internally
libvirt_net: 'openshift'
libvirt_kstemplate: "rhel8.cfg.j2"
libvirt_ksfile: "/tmp/{{ libvirt_name }}.cfg"
libvirt_boot_order: "hd,cdrom,network,menu=on"
#libvirt_cpu_model: "qemu64"
libvirt_cpu_model: "host"