---
# playbook to create openshift cluster
- name: Create bootstrap machine
  hosts: bootstrap
  connection: local
  vars:
    port: 22623
  roles:
    - role: virt-install
      vars:
        port: 22623

- name: Create control plane
  hosts: masters
  connection: local
  vars:
    ocp_cluster_dir: "{{ocp_base_dir}}/{{ocp_name}}"
  roles:
    - role: virt-install
      vars:
        port: 22623
  tasks:
    - name: Wait for bootstrap process
      command: openshift-install wait-for bootstrap-complete
      args:
        chdir: "{{ ocp_cluster_dir}}"
      async: 1800
      poll: 0
      register: bootstrap_bg
      delegate_to: helper

    - name: Wait for bootstrap to complete
      async_status: jid={{ bootstrap_bg.ansible_job_id }}
      register: job_result
      until: job_result.finished
      retries: 120
      delay: 30 
      delegate_to: helper


- name: Create workers
  hosts: workers
  connection: local
  roles:
    - role: virt-install
      vars:
        port: 10250

- name: Wait for the installation to complete
  hosts: helper
  vars:
    kubeconfig: "{{ ocp_base_dir + '/' + ocp_name + '/auth/kubeconfig' }}"
    ocp_cluster_dir: "{{ocp_base_dir}}/{{ocp_name}}"
  tasks:
    - name: Running openshift-install wait-for install-complete
      command: openshift-install wait-for install-complete
      args:
        chdir: "{{ ocp_cluster_dir}}"
      async: 1800
      poll: 0
      register: install_bg

    - name: Approve first set of CSR from workers
      shell: "oc --config={{ kubeconfig }} get csr | grep -i pending | cut -f 1 -d ' ' | xargs -n 1 oc --config={{ kubeconfig }} adm certificate approve"

    - wait_for:
        timeout: 5

    - name: Approve second set of CSR from workers
      shell: "oc --config={{ kubeconfig }} get csr | grep -i pending | cut -f 1 -d ' ' | xargs -n 1 oc --config={{ kubeconfig }} adm certificate approve"

    - name: Cluster install complete
      async_status: jid={{ install_bg.ansible_job_id }}
      register: job_result
      until: job_result.finished
      retries: 80
      delay: 10


- name: Remove bootstrap
  hosts: bootstrap
  connection: local
  roles:
    - virt-remove
