---
# playbook to create openshift cluster
- name: Create bootstrap machine
  hosts: bootstrap
  connection: local
  roles:
    - virt-install

- name: Create control plane
  hosts: masters
  connection: local
  roles:
    - virt-install

- name: Wait for bootstrap process
  hosts: helper
  tasks:
    - set_fact: 
        ocp_cluster_dir: "{{ocp_base_dir}}/{{ocp_name}}"

    - name: openshift-install wait-for bootstrap-complete
      command: openshift-install wait-for bootstrap-complete
      args:
        chdir: "{{ ocp_cluster_dir}}"
      async: 1000
      poll: 0
      register: bootstrap_bg

    - name: Wait for bootstrap to complete
      async_status: jid={{ bootstrap_bg.ansible_job_id }}
      register: job_result
      until: job_result.finished
      retries: 80
      delay: 15

#    - debug:
#        msg: "Monitoring file {{ ocp_install_log }}"
#
#    - name: Bootstrap is complete 
#      wait_for:
#        path: "{{ ocp_install_log }}"
#        search_regex: "Bootstrap status: complete"
#        timeout: 600

- name: Create workers
  hosts: workers
  connection: local
  roles:
    - virt-install

- name: Remove bootstrap
  hosts: bootstrap
  connection: local
  roles:
    - virt-remove

- name: Wait for installation process
  hosts: helper
  tasks:
    - name: openshift-install wait-for install-complete
      command: openshift-install wait-for install-complete
      args:
        chdir: "{{ ocp_cluster_dir}}"
      async: 1000
      poll: 0
      register: install_bg

    - name: Wait for install to complete
      async_status: jid={{ install_bg.ansible_job_id }}
      register: job_result
      until: job_result.finished
      retries: 80
      delay: 15

#- name: Wait for install complete
#  hosts: bastion
#  connection: local
#  become: yes
#  vars:
#    ocp_install_log: "{{ ocp_dir + '/' + ocp_name + '/.openshift_install.log' }}"
#  tasks:
#    - debug:
#        msg: "Monitoring file {{ ocp_install_log }}"
#
#    - name: Install is complete 
#      wait_for:
#        path: "{{ ocp_install_log }}"
#        search_regex: "Install status: complete"