---
#  vars
matchbox_ver: 'v0.8.0'
matchbox_tarball: "{{ 'matchbox-' + matchbox_ver + '-linux-amd64.tar.gz' }}"
matchbox_url: "{{ 'https://github.com/poseidon/matchbox/releases/download/' + matchbox_ver + '/' + matchbox_tarball }}"
matchbox_tmp: "{{ '/tmp/matchbox-' + matchbox_ver + '-linux-amd64' }}"
matchbox_dir: "/var/lib/matchbox"
matchbox_assets: "{{ matchbox_dir + '/assets' }}"
matchbox_groups: "{{ matchbox_dir + '/groups' }}"
matchbox_ignition: "{{ matchbox_dir + '/ignition' }}"
matchbox_profiles: "{{ matchbox_dir + '/profiles' }}"
